export const CONST_STORE_WINDOW = {
  TOP_PREV_WINDOW: 1,
  LEFT_PREV_WINDOW: 1,
  WIDTH_WINDOW: 40,
  HEIGHT_WINDOW: 45
};

export const CONST_STORE_WORKSPACE = {
  TOP_PREV_SHORTCUT: 5,
  LEFT_PREV_SHORTCUT: 5,
  WIDTH_SHORTCUT: 100,
  HEIGHT_SHORTCUT: 100,
  STEP_SHIFT: 120,
  URL_SAVE_SETTINGS_DESKTOP: "/extusers/fpage/savedesktop/"
};
